# Include Makefile for clock configuration
include source/drivers/system_clock/Makefile

# Include Makefile for GPIO configuration
include source/drivers/GPIO/Makefile

# Include Makefile for UART configuration
include source/drivers/UART/Makefile